name: "testci"

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  test_ci:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Работает после успешного CI"
